version: '3'
services:
  # Espacio para tu apigateway
  nginx:
    image: nginx:latest
    ports:
      - 5000:5000
    volumes:
        - ./api-gateway/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
        - server-x
        - monitor
    networks:
      network:

  # Servidor principal con codigo de servicio de registro de usuarios
  server-x:
    image: alpine:latest
    command: /bin/sh -c "while :; do sleep 10; done"

  monitor:
    build:
      context: ./monitor
    environment:
      # Este es el nombre del servidor principal
      - SERVER_X_NAME=server-x
      # Esta imagen te la debe proporcionar Emerson, es la imagen del servidor 
      # del codigo fuente (servicio de registro de usuario)
      - SERVER_X_IMAGE=alpine:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  
    networks:
      network:

networks:
  network:
