version: '3'
services:
  # Espacio para tu apigateway
  nginx:
    image: nginx:latest
    ports:
      - 5000:5000
    volumes:
        - ./api-gateway/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
        - monitor
        - registro_usuario
        - consulta_usuario
    networks:
      network:

  # Servidor principal con codigo de servicio de registro de usuarios
  registro_usuario:
    build:
      context: ./registro_usuario
    ports:
      - "5002:5002"

  consulta_usuario:
    build:
      context: ./consulta_usuario
    ports:
      - "5001:5001"

  monitor:
    build:
      context: ./monitor
    environment:
      # Este es el nombre del servidor principal
      - SERVER_X_NAME=registro_usuario-1
      # Esta imagen te la debe proporcionar Emerson, es la imagen del servidor 
      # del codigo fuente (servicio de registro de usuario)
      - SERVER_X_IMAGE=alpine:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  
    networks:
      network:

networks:
  network:
