version: '3'
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"

  db_usuario:
    build: db_usuario
    ports:
      - "5004:5004"
    environment:
      FLASK_APP: app
      FLASK_DEBUG: 1
      FLASK_ENV: development

  autenticador:
    build: autenticador
    volumes:
      - ./autenticador:/app
    ports:
      - "5001:5001"

  registro_usuario:
    build: registro_usuario
    volumes:
      - ./registro_usuario:/app
    ports:
      - "5002:5002"
    depends_on:
      - db_usuario
      - rabbitmq

  consulta_usuario:
    build: consulta_usuario
    volumes:
      - ./consulta_usuario:/app
    ports:
      - "5003:5003"
    depends_on:
      - db_usuario
      - rabbitmq      